disabled = false
locale = "en"
label = "English"
weight = 1
title = "Tim Herpich"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Welcome to the personal website of Tim Herpich."

[params.author]
name = "Tim Herpich"
image = "images/avatar.png"
headline = "Risk & Technology Manager in Insurance and Asset Management | PhD, MBA, CFA"
bio = "Risk & Technology Manager in Insurance and Asset Management | PhD, MBA, CFA"
links = [
  { email = "tim.herpich@d-fine.com" },
  { linkedin = "https://www.linkedin.com/in/timherpich" },
  { github = "https://github.com/tim-herpich" },
  { orcid = "https://orcid.org/0000-0002-2749-2557" }
]
