# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      classes: wide
      sidebar:
        nav: "posts"

# header, + specs in _data/navigation.yml
title: Tim Herpich
# subtitle: "Personal Website"

# author profile as side bar
author:
  name: Tim Herpich
  avatar: /assets/images/avatar.png
  bio: Consultant Risk Management and Software Engineering.
  # email: tim.herpich@d-fine.com
  location: Zurich, Switzerland
  links:
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/timherpich
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/tim-herpich
    - label: ORCID
      # icon: "fab fa-fw fa-github"
      url: https://orcid.org/0000-0002-2749-2557

# footer
footer:
  links:
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/timherpich
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/tim-herpich
    - label: ORCID
      # icon: "fab fa-fw fa-github"
      url: https://orcid.org/0000-0002-2749-2557


description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the personal website of Tim Herpich!
  Here, you'll find an in-depth look at my academic contributions in theoretical physics (stochatic thermodynamics) and my journey as a consultant in the financial industry.
  This site is designed to be a hub for sharing my work, connecting with like-minded professionals, and exploring innovative ideas.
  Discover more about me and my journey as you navigate through the sections of this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://tim-herpich.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
repository: tim-herpich/tim-herpich.github.io
# logo: /assets/images/masthead_logo.png
atom_feed:
  hide: false
show_email: false # Set to false to disable email

# Build settings
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "air" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed

collections:
  publications:
    output: true
    permalink: /publications/items/:title/
    sort_by: "year"
  talks:
    output: true
    permalink: /talks/items/:title/
    sort_by: "year"
